name: ebrarswebsite
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_image_slideshow: ^0.1.4
 
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/logos/
    - assets/images/background/background.png
    - assets/images/app_images/
    - assets/pdf/ebrarsresume.pdf
    
